name: HashiCorp Vault Secrets
author: Arky Asmal
description: Access HashiCorp Vault Secrets deployed on the HashiCorp Cloud Platform, with increased support and customization. This is not to be confused with a self-hosted Hashicorp Vault Instance, which already has a Github action.
inputs: 
  CLIENT_ID: 
    default: '' 
    description: Client ID of the HashiCorp Cloud Service Principal/User
    required: true
  CLIENT_SECRET:
    default: '' 
    description: Client Secret of the HashiCorp Cloud Service Principal/User
    required: true
  PROJECT_NAME:
    default: ''  
    description: Name of project deployed on HashiCorp Cloud Platform
    required: true
  APP_NAME: 
    default: '' 
    description: Name of app deployed on HashiCorp Cloud Platform, using HashiCorp Vault Secrets
    required: true
  SECRET_NAMES: 
    default: '[]'
    description: a list of secret names, in an app using HashiCorp Vault Secrets
    required: true
  GENERATE_ENV:
    default: 'false'
    description: a boolean value, that determines whether to generate .env file or not. By default, this is set to false.
    required: false
runs: 
  using: 'node20'
  main: 'dist/action/index.js'