name: HashiCorp Vault Secrets
author: Arky Asmal
description: Access secrets stored on HashiCorp Vault Secrets, in the HashiCorp Cloud Platform.
inputs: 
  CLIENT_ID: 
    default: '' 
    description: Client ID of the HashiCorp Cloud Service Principal/User
    required: true
  CLIENT_SECRET:
    default: '' 
    description: Client Secret of the HashiCorp Cloud Service Principal/User
    required: true
  ORGANIZATION_NAME:
    default: '' 
    description: Name of the HashiCorp Cloud Organization
    required: true
  PROJECT_NAME:
    default: ''  
    description: Name of project deployed on HashiCorp Cloud Platform
    required: true
  APP_NAME: 
    default: '' 
    description: Name of app deployed on HashiCorp Cloud Platform, using HashiCorp Vault Secrets
    required: true
  SECRET_NAMES: 
    default: "[]"
    description: a list of secret names, in an app using HashiCorp Vault Secrets
    required: true
  GENERATE_ENV:
    default: ''
    description: The name of the .env file to be generated. If not set, no .env is generated. By default this is not set.
    required: false
runs: 
  using: 'node20'
  main: 'dist/action/index.js'
